"""
Bounded SQL shard writer.

Migration SQL generators used to write one unbounded file per step, which
forced the whole step to be extracted, generated, and executed in memory and
in one transaction. ``ShardWriter`` instead accumulates generated SQL "units"
(one unit per source row, or per batched group of rows) and rolls over to a
new file whenever a row-count or byte-size threshold is exceeded.

Every shard file is self-contained and safe to execute independently and more
than once:
  - It repeats the step preamble (encoding/extension setup + idempotent
    ``migration`` schema bootstrap), so a worker can run any shard without
    needing another shard's setup statements to have run first.
  - Row-level INSERTs generated by ``utils.sql_generator`` are already
    idempotent (``ON CONFLICT`` / ``NOT EXISTS`` guards), so re-running a
    shard after a partial failure is safe.

The trailing "epilogue" (validation blocks, batch-completion bookkeeping,
readiness reconciliation, etc.) is merged into the last shard only, exactly
matching the single-file behaviour these generators had before sharding was
introduced. For the common case where all rows fit in one shard, the output
is byte-for-byte equivalent to the previous single-file output.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Iterable, List, Optional


DEFAULT_MAX_ROWS_PER_SHARD = 1000
DEFAULT_MAX_BYTES_PER_SHARD = 8 * 1024 * 1024  # 8 MB


@dataclass
class ShardInfo:
    shard_index: int
    file_path: str
    expected_rows: int
    byte_size: int
    checksum: str
    owner_legacy_ids: List[str] = field(default_factory=list)
    owner_scope_complete: bool = True


@dataclass
class ShardManifest:
    step_key: str
    target_database: str
    migration_run_id: Optional[str]
    shards: List[ShardInfo] = field(default_factory=list)
    total_rows: int = 0
    generated_at: str = ""

    def to_dict(self) -> dict:
        return {
            "step_key": self.step_key,
            "target_database": self.target_database,
            "migration_run_id": self.migration_run_id,
            "total_rows": self.total_rows,
            "total_shards": len(self.shards),
            "generated_at": self.generated_at,
            "shards": [
                {
                    "shard_index": shard.shard_index,
                    "file_path": shard.file_path,
                    "expected_rows": shard.expected_rows,
                    "byte_size": shard.byte_size,
                    "checksum": shard.checksum,
                    "owner_legacy_ids": shard.owner_legacy_ids,
                    "owner_scope_complete": shard.owner_scope_complete,
                }
                for shard in self.shards
            ],
        }

    @property
    def primary_file(self) -> Optional[str]:
        """Path of the first shard, kept for backward-compatible single-file callers."""
        return self.shards[0].file_path if self.shards else None

    def save(self, manifest_path: str) -> str:
        os.makedirs(os.path.dirname(manifest_path) or ".", exist_ok=True)
        tmp_path = manifest_path + ".tmp"
        with open(tmp_path, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
        os.replace(tmp_path, manifest_path)
        return manifest_path


def manifest_path_for(output_file: str) -> str:
    return output_file + ".manifest.json"


def load_manifest(manifest_path: str) -> ShardManifest:
    with open(manifest_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    manifest = ShardManifest(
        step_key=data["step_key"],
        target_database=data["target_database"],
        migration_run_id=data.get("migration_run_id"),
        total_rows=data.get("total_rows", 0),
        generated_at=data.get("generated_at", ""),
    )
    manifest.shards = [
        ShardInfo(
            shard_index=item["shard_index"],
            file_path=item["file_path"],
            expected_rows=item["expected_rows"],
            byte_size=item["byte_size"],
            checksum=item["checksum"],
            owner_legacy_ids=list(item.get("owner_legacy_ids", [])),
            owner_scope_complete=bool(item.get("owner_scope_complete", False)),
        )
        for item in data.get("shards", [])
    ]
    return manifest


def checksum_file(file_path: str) -> str:
    with open(file_path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


class ShardWriter:
    """Accumulates generated SQL units and writes bounded, atomic shard files."""

    def __init__(
        self,
        output_file: str,
        step_key: str,
        target_database: str,
        migration_run_id: Optional[str],
        preamble: str,
        max_rows_per_shard: int = DEFAULT_MAX_ROWS_PER_SHARD,
        max_bytes_per_shard: int = DEFAULT_MAX_BYTES_PER_SHARD,
    ):
        self.output_file = output_file
        self.dir = os.path.dirname(output_file) or "."
        self.stem = os.path.splitext(os.path.basename(output_file))[0]
        self.step_key = step_key
        self.target_database = target_database
        self.migration_run_id = migration_run_id
        self.preamble = preamble
        self.max_rows = max(1, max_rows_per_shard)
        self.max_bytes = max(1024, max_bytes_per_shard)

        os.makedirs(self.dir, exist_ok=True)

        self._buffer_parts: List[str] = []
        self._buffer_bytes = 0
        self._buffer_rows = 0
        self._buffer_owner_legacy_ids: set[str] = set()
        self._buffer_owner_scope_complete = True
        self._shard_index = 0
        self._shards: List[ShardInfo] = []
        self._total_rows = 0
        self._closed = False

    def write_unit(
        self,
        sql_text: str,
        weight: int = 1,
        owner_legacy_ids: Optional[Iterable[str]] = None,
    ) -> None:
        """Append one generated SQL unit (e.g. one row's INSERT block).

        ``weight`` lets a single write represent more than one logical row
        (e.g. a batched multi-row INSERT), so shard sizing stays meaningful.
        """
        if self._closed:
            raise RuntimeError("Cannot write to a finalized ShardWriter")
        if not sql_text:
            return
        encoded_len = len(sql_text.encode("utf-8")) + 1
        if self._buffer_rows > 0 and (
            self._buffer_rows + weight > self.max_rows
            or self._buffer_bytes + encoded_len > self.max_bytes
        ):
            self._flush(final=False)
        self._buffer_parts.append(sql_text)
        self._buffer_parts.append("\n")
        self._buffer_bytes += encoded_len
        self._buffer_rows += weight
        self._total_rows += weight
        normalized_owner_ids = [
            str(owner_id)
            for owner_id in (owner_legacy_ids or [])
            if owner_id is not None and str(owner_id)
        ]
        self._buffer_owner_legacy_ids.update(normalized_owner_ids)
        if weight > 0 and not normalized_owner_ids:
            self._buffer_owner_scope_complete = False

    def _shard_path(self, index: int) -> str:
        if index == 1:
            return self.output_file
        return os.path.join(self.dir, f"{self.stem}.shard{index:04d}.sql")

    def _flush(self, final: bool, epilogue: str = "") -> None:
        self._shard_index += 1
        path = self._shard_path(self._shard_index)
        content = self.preamble + "".join(self._buffer_parts)
        if final and epilogue:
            content += epilogue
        tmp_path = path + ".tmp"
        with open(tmp_path, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
        os.replace(tmp_path, path)
        checksum = hashlib.sha256(content.encode("utf-8")).hexdigest()
        self._shards.append(
            ShardInfo(
                shard_index=self._shard_index,
                file_path=path,
                expected_rows=self._buffer_rows,
                byte_size=len(content.encode("utf-8")),
                checksum=checksum,
                owner_legacy_ids=sorted(self._buffer_owner_legacy_ids),
                owner_scope_complete=self._buffer_owner_scope_complete,
            )
        )
        self._buffer_parts = []
        self._buffer_bytes = 0
        self._buffer_rows = 0
        self._buffer_owner_legacy_ids = set()
        self._buffer_owner_scope_complete = True

    def _append_epilogue_to_last_shard(self, epilogue: str) -> None:
        last = self._shards[-1]
        with open(last.file_path, "r", encoding="utf-8", newline="") as fh:
            content = fh.read()
        content += epilogue
        tmp_path = last.file_path + ".tmp"
        with open(tmp_path, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
        os.replace(tmp_path, last.file_path)
        last.byte_size = len(content.encode("utf-8"))
        last.checksum = hashlib.sha256(content.encode("utf-8")).hexdigest()

    def finalize(self, epilogue: str = "") -> ShardManifest:
        """Flush any pending rows, merge the epilogue, and return the manifest.

        Does not write the manifest file itself; call ``manifest.save(...)``.
        """
        if self._closed:
            raise RuntimeError("ShardWriter already finalized")
        self._closed = True

        if self._buffer_rows > 0 or not self._shards:
            self._flush(final=True, epilogue=epilogue)
        elif epilogue:
            self._append_epilogue_to_last_shard(epilogue)

        manifest = ShardManifest(
            step_key=self.step_key,
            target_database=self.target_database,
            migration_run_id=self.migration_run_id,
            shards=self._shards,
            total_rows=self._total_rows,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )
        return manifest

    @property
    def shard_count(self) -> int:
        return len(self._shards) if self._closed else self._shard_index + (1 if self._buffer_rows else 0)


class ShardWriterFileAdapter:
    """File-like facade over a :class:`ShardWriter`.

    Lets generator functions that emit several ``sql_file.write(...)`` calls
    per logical row (e.g. batched multi-row INSERTs) keep that code
    unchanged. Wrap the group with ``begin_unit()``/``end_unit()`` so all
    writes in between are committed to the shard writer as a single sized
    unit; writes outside of a unit are committed immediately with zero
    weight (they never trigger a shard rollover on their own).
    """

    def __init__(self, shard_writer: ShardWriter):
        self._writer = shard_writer
        self._pending: List[str] = []
        self._in_unit = False
        self._weight = 0
        self._owner_legacy_ids: List[str] = []

    def write(self, text: str) -> None:
        if text:
            self._pending.append(text)
        if not self._in_unit:
            self._flush(weight=0)

    def begin_unit(
        self,
        weight: int = 1,
        owner_legacy_ids: Optional[Iterable[str]] = None,
    ) -> None:
        if self._in_unit:
            raise RuntimeError("begin_unit() called while a unit is already open")
        self._in_unit = True
        self._weight = weight
        self._owner_legacy_ids = list(owner_legacy_ids or [])

    def end_unit(self) -> None:
        if not self._in_unit:
            raise RuntimeError("end_unit() called without a matching begin_unit()")
        self._in_unit = False
        weight, self._weight = self._weight, 0
        owner_legacy_ids, self._owner_legacy_ids = self._owner_legacy_ids, []
        self._flush(weight=weight, owner_legacy_ids=owner_legacy_ids)

    def _flush(
        self,
        weight: int,
        owner_legacy_ids: Optional[Iterable[str]] = None,
    ) -> None:
        if self._pending:
            self._writer.write_unit(
                "".join(self._pending),
                weight=weight,
                owner_legacy_ids=owner_legacy_ids,
            )
            self._pending = []
